import colors from "../../../../tokens/global/colors";

export default {
  'bg.primary': colors.base.white,
  'bg.primary.alt': colors.base.white,
  'bg.primary.hover': colors.grayLight[50],
  'bg.primary.solid': colors.grayLight[950],
  'bg.secondary': colors.grayLight[50],
  'bg.secondary.alt': colors.grayLight[50],
  'bg.secondary.hover': colors.grayLight[100],
  'bg.secondary.subtle': colors.grayLight[25],
  'bg.secondary.solid': colors.grayLight[600],
  'bg.tertiary': colors.grayLight[100],
  'bg.quaternary': colors.grayLight[200],
  'bg.active': colors.grayLight[50],
  'bg.disabled': colors.grayLight[100],
  'bg.disabled.subtle': colors.grayLight[50],
  'bg.overlay': colors.grayLight[950],
  'bg.brand.primary': colors.brand[50],
  'bg.brand.primary.alt': colors.grayLight[50],
  'bg.brand.secondary': colors.brand[100],
  'bg.brand.solid': colors.brand[600],
  'bg.brand.solid.hover': colors.brand[700],
  'bg.brand.section': colors.grayLight[800],
  'bg.brand.section.subtle': colors.grayLight[700],
  'bg.error.primary': colors.error[50],
  'bg.error.secondary': colors.error[100],
  'bg.error.solid': colors.error[600],
  'bg.warning.primary': colors.warning[50],
  'bg.warning.secondary': colors.warning[100],
  'bg.warning.solid': colors.warning[600],
  'bg.success.primary': colors.success[50],
  'bg.success.secondary': colors.success[100],
  'bg.success.solid': colors.success[600],
};
