import colors from "../../../../tokens/global/colors";

export default {
  'button.primary.bg': colors.blueDark[600],
  'button.primary.bg.hover': colors.blueDark[700],
  'button.primary.fg': colors.base.white,
  'button.primary.fg.hover': colors.base.white,
  'button.secondary.bg': colors.base.white,
  'button.secondary.bg.hover': colors.grayLight[50],
  'button.secondary.fg': colors.grayLight[700],
  'button.secondary.fg.hover': colors.grayLight[800],
  'button.secondary.border': colors.grayLight[300],
  'button.secondary.border.hover': colors.grayLight[300],
  'button.secondary.color.bg': colors.base.white,
  'button.secondary.color.bg.hover': colors.blueDark[50],
  'button.secondary.color.border': colors.blueDark[300],
  'button.secondary.color.border.hover': colors.blueDark[300],
  'button.secondary.color.fg': colors.blueDark[700],
  'button.secondary.color.fg.hover': colors.blueDark[800],
  'button.primary.error.fg': colors.base.white,
  'button.primary.error.fg.hover': colors.base.white,
  'button.primary.error.bg': colors.error[600],
  'button.primary.error.bg.hover': colors.error[700],
  'button.secondary.error.fg': colors.error[700],
  'button.secondary.error.fg.hover': colors.error[800],
  'button.secondary.error.bg': colors.base.white,
  'button.secondary.error.bg.hover': colors.error[50],
  'button.secondary.error.border': colors.error[300],
  'button.secondary.error.border.hover': colors.error[300],
  'button.tertiary.fg': colors.grayLight[600],
  'button.tertiary.fg.hover': colors.grayLight[700],
  'button.tertiary.bg.hover': colors.grayLight[50],
  'button.tertiary.color.fg': colors.blueDark[700],
  'button.tertiary.color.fg.hover': colors.blueDark[800],
  'button.tertiary.color.bg.hover': colors.blueDark[50],
  'button.tertiary.error.fg': colors.error[700],
  'button.tertiary.error.fg.hover': colors.error[800],
  'button.tertiary.error.bg.hover': colors.error[50],
};
