import colors from "../../../../tokens/global/colors";

export default {
  'bg.primary': colors.grayDark[950],
  'bg.primary.alt': colors.grayDark[900],
  'bg.primary.hover': colors.grayDark[800],
  'bg.primary.solid': colors.grayDark[900],
  'bg.secondary': colors.grayDark[900],
  'bg.secondary.alt': colors.grayDark[950],
  'bg.secondary.hover': colors.grayDark[800],
  'bg.secondary.subtle': colors.grayDark[900],
  'bg.secondary.solid': colors.grayDark[600],
  'bg.tertiary': colors.grayDark[800],
  'bg.quaternary': colors.grayDark[700],
  'bg.active': colors.grayDark[800],
  'bg.disabled': colors.grayDark[800],
  'bg.disabled.subtle': colors.grayDark[900],
  'bg.overlay': colors.grayDark[800],
  'bg.brand.primary': colors.brand[500],
  'bg.brand.primary.alt': colors.grayDark[800],
  'bg.brand.secondary': colors.brand[600],
  'bg.brand.solid': colors.brand[600],
  'bg.brand.solid.hover': colors.brand[500],
  'bg.brand.section': colors.grayDark[800],
  'bg.brand.section.subtle': colors.grayDark[950],
  'bg.error.primary': colors.error[500],
  'bg.error.secondary': colors.error[600],
  'bg.error.solid': colors.error[600],
  'bg.warning.primary': colors.warning[500],
  'bg.warning.secondary': colors.warning[600],
  'bg.warning.solid': colors.warning[600],
  'bg.success.primary': colors.success[500],
  'bg.success.secondary': colors.success[600],
  'bg.success.solid': colors.success[600],
};
