import colors from "../../../../tokens/global/colors";

export default {
  'button.primary.bg': colors.blueDark[600],
  'button.primary.bg.hover': colors.blueDark[700],
  'button.primary.fg': colors.base.white,
  'button.primary.fg.hover': colors.base.white,
  'button.secondary.bg': colors.grayDark[900],
  'button.secondary.bg.hover': colors.grayDark[800],
  'button.secondary.fg': colors.grayDark[300],
  'button.secondary.fg.hover': colors.grayDark[100],
  'button.secondary.border': colors.grayDark[700],
  'button.secondary.border.hover': colors.grayDark[700],
  'button.secondary.color.bg': colors.grayDark[900],
  'button.secondary.color.bg.hover': colors.grayDark[800],
  'button.secondary.color.border.hover': colors.grayDark[700],
  'button.secondary.color.border': colors.grayDark[700],
  'button.secondary.color.fg': colors.grayDark[300],
  'button.secondary.color.fg.hover': colors.grayDark[100],
  'button.primary.error.fg': colors.base.white,
  'button.primary.error.fg.hover': colors.base.white,
  'button.primary.error.bg': colors.error[600],
  'button.primary.error.bg.hover': colors.error[700],
  'button.secondary.error.fg': colors.error[200],
  'button.secondary.error.fg.hover': colors.error[100],
  'button.secondary.error.bg': colors.error[950],
  'button.secondary.error.bg.hover': colors.error[900],
  'button.secondary.error.border': colors.error[800],
  'button.secondary.error.border.hover': colors.error[700],
  'button.tertiary.fg': colors.grayDark[400],
  'button.tertiary.fg.hover': colors.grayDark[200],
  'button.tertiary.bg.hover': colors.grayDark[800],
  'button.tertiary.color.fg': colors.grayDark[300],
  'button.tertiary.color.fg.hover': colors.grayDark[100],
  'button.tertiary.color.bg.hover': colors.grayDark[800],
  'button.tertiary.error.fg': colors.error[300],
  'button.tertiary.error.fg.hover': colors.error[200],
  'button.tertiary.error.bg.hover': colors.error[900],
};
