import raw from "../../../tokens/global/colors";

const crmOverlay = {
  "bg.canvas": raw.mist[950],
  "bg.surface": raw.mist[900],
  "bg.surface.muted": raw.mist[800],
  "bg.surface.raised": raw.mist[800],
  "bg.brand.subtle": raw.evergreen[900],
  "bg.brand.solid": raw.evergreen[500],
  "bg.brand.hover": raw.evergreen[400],
  "bg.danger.subtle": raw.coral[700],
  "bg.danger.solid": raw.coral[500],
  "bg.warning.subtle": raw.amber[700],
  "bg.warning.solid": raw.amber[400],
  "bg.info.subtle": raw.sky[600],
  "bg.info.solid": raw.sky[400],

  "text.primary": raw.mist[25],
  "text.secondary": raw.mist[300],
  "text.muted": raw.mist[400],
  "text.inverse": raw.mist[950],
  "text.brand": raw.evergreen[300],
  "text.danger": raw.coral[300],
  "text.warning": raw.amber[300],
  "text.success": raw.evergreen[300],
  "text.link": raw.evergreen[300],

  "border.subtle": raw.mist[800],
  "border.default": raw.mist[700],
  "border.strong": raw.mist[600],
  "border.brand": raw.evergreen[500],
  "border.danger": raw.coral[500],
  "border.focus": raw.evergreen[400],

  "button.primary.bg": raw.evergreen[500],
  "button.primary.bg.hover": raw.evergreen[400],
  "button.primary.bg.active": raw.evergreen[300],
  "button.primary.text": raw.mist[950],
  "button.secondary.bg": raw.mist[800],
  "button.secondary.bg.hover": raw.mist[700],
  "button.secondary.border": raw.mist[600],
  "button.secondary.text": raw.mist[50],
  "button.ghost.bg.hover": raw.evergreen[900],
  "button.ghost.text": raw.evergreen[300],
  "button.danger.bg": raw.coral[500],
  "button.danger.bg.hover": raw.coral[400],
  "button.danger.text": raw.base.white,

  "input.bg": raw.mist[900],
  "input.border": raw.mist[700],
  "input.border.hover": raw.mist[600],
  "input.border.focus": raw.evergreen[400],
  "input.placeholder": raw.mist[500],
  "input.text": raw.mist[25],
  "input.disabled.bg": raw.mist[800],

  "stage.em_atendimento.bg": raw.sky[600],
  "stage.em_atendimento.text": raw.sky[100],
  "stage.em_negociacao.bg": raw.evergreen[800],
  "stage.em_negociacao.text": raw.evergreen[100],
  "stage.aguardando_fechamento.bg": raw.amber[700],
  "stage.aguardando_fechamento.text": raw.amber[100],
  "stage.fechado.bg": raw.evergreen[900],
  "stage.fechado.text": raw.evergreen[100],
  "stage.nao_fechado.bg": raw.coral[700],
  "stage.nao_fechado.text": raw.coral[100],

  "mode.ai.bg": raw.sand[500],
  "mode.ai.text": raw.sand[50],
  "mode.human.bg": raw.evergreen[800],
  "mode.human.text": raw.evergreen[100],

  "nav.bg": "rgba(16,22,18,0.92)",
  "nav.item.active.bg": raw.evergreen[900],
  "nav.item.active.text": raw.evergreen[200],
  "nav.item.text": raw.mist[300],
} as const;

export default crmOverlay;
